services:
  - type: web
    name: legal-case-management
    env: node
    plan: free
    buildCommand: node render-build.js
    startCommand: node render-start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false