services:
  - type: web
    name: manager-juri-base
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: node start-production.js
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production