services:
  - type: web
    name: legal-case-management
    env: node
    buildCommand: npm install && npx vite build && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production